# permissions for end users to view balancerpolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: balancerx
    app.kubernetes.io/managed-by: kustomize
  name: balancerpolicy-viewer-role
rules:
- apiGroups:
  - balancerx.io
  resources:
  - balancerpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - balancerx.io
  resources:
  - balancerpolicies/status
  verbs:
  - get
