# permissions for end users to edit balancerpolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: balancerx
    app.kubernetes.io/managed-by: kustomize
  name: balancerpolicy-editor-role
rules:
- apiGroups:
  - balancerx.balancerx.io
  resources:
  - balancerpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - balancerx.balancerx.io
  resources:
  - balancerpolicies/status
  verbs:
  - get
