---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - balancerx.balancerx.io
  resources:
  - balancerpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - balancerx.balancerx.io
  resources:
  - balancerpolicies/finalizers
  verbs:
  - update
- apiGroups:
  - balancerx.balancerx.io
  resources:
  - balancerpolicies/status
  verbs:
  - get
  - patch
  - update
