apiVersion: balancerx.io/v1alpha1
kind: BalancerPolicy
metadata:
  name: jobs-dispatcher
spec:
  sourceNamespace: inbox-jobs
  # Load‑balancing strategy (ringhash | roundrobin | leastconn)
  balancer: ringhash
  # Target GVR (group/version/resource)
  gvr: mygroup.io/v1/examplejobs
