apiVersion: balancerx.io/v1alpha1
kind: BalancerPolicy
metadata:
  name: jobs-dispatcher-8
spec:
  sourceNamespace: inbox-jobs-9
  # Load‑balancing strategy (ringhash | roundrobin | leastconn)
  balancer: roundrobin
  # Target GVR (group/version/resource)
  gvr: demo.bastion.io/v1/tasks
