apiVersion: balancerx.balancerx.io/v1alpha1
kind: BalancerPolicy
metadata:
  labels:
    app.kubernetes.io/name: balancerx
    app.kubernetes.io/managed-by: kustomize
  name: balancerpolicy-sample
spec:
  # TODO(user): Add fields here
