apiVersion: balancerx.io/v1alpha1
kind: BalancerPolicy
metadata:
  name: cr-cloud-operator-1
spec:
  sourceNamespace: cloud-operator-cr-queue
  # Load‑balancing strategy (ringhash | roundrobin | leastconn)
  balancer: ringhash
  replicas: 4
  group: mycompany.io
